### ISSUE TITLE
Memory usage issue

### ISSUE THREAD

**Issue by EJHyun** [sharkmir1/T-GAP#2]
I ran 
python main.py --dataset=data/wikidata11k_aug --run=wikidata11k --num_sample_from=50 --max_num_neighbor=200 --grad_clip=4 --batch_size=1 --device=cpu

with 64GB RAM.

But the memory wasn't enough.

![image](https://user-images.githubusercontent.com/56884260/128695246-45857da3-7254-4fea-b155-a9ff30bfece2.png)
(Initial RAM usage)

![image](https://user-images.githubusercontent.com/56884260/128695345-a229802a-033e-4d32-a34d-7203df68e624.png)
(Last RAM usage right before the failure)

README says you used 1 Tesla V100.
Tesla V100's memory capacity is 16GB or 32GB..

But my 64GB RAM failed..
why?

**Comment by jaehunjung1** [comment]
Note that an env with cpu ram and vram could be different. DGL lib is known for heterogeneous mem usage depending on whether it's ran on cpu or gpu, I suggest you try running it on gpu with the same setting.

**Comment by EJHyun** [comment]
> Note that an env with cpu ram and vram could be different. DGL lib is known for heterogeneous mem usage depending on whether it's ran on cpu or gpu, I suggest you try running it on gpu with the same setting.

Wow thank you for your quick reply!

But sadly i've already tried with 12GB GPU before using CPU,
but it failed... with the setting

python main.py --dataset=data/wikidata11k_aug --run=wikidata11k --num_sample_from=50 --max_num_neighbor=200 --grad_clip=4 --batch_size=1

If you don't mind, 
Can you tell me the total trianing time for each 3 datasets (ICEWS14, ICEWS05-15, and WIKIDATA11k)
and the exact memory capacity of your GPU?

Thank you!

**Comment by Davidchenw** [comment]
> > Note that an env with cpu ram and vram could be different. DGL lib is known for heterogeneous mem usage depending on whether it's ran on cpu or gpu, I suggest you try running it on gpu with the same setting.
> 
> Wow thank you for your quick reply!
> 
> But sadly i've already tried with 12GB GPU before using CPU, but it failed... with the setting
> 
> python main.py --dataset=data/wikidata11k_aug --run=wikidata11k --num_sample_from=50 --max_num_neighbor=200 --grad_clip=4 --batch_size=1
> 
> If you don't mind, Can you tell me the total trianing time for each 3 datasets (ICEWS14, ICEWS05-15, and WIKIDATA11k) and the exact memory capacity of your GPU?
> 
> Thank you!

I also encountered the same problem, can you find a solution?
